name=ControlloPID
version=0.1
author=Marco Ferro
maintainer=Marco Ferro marcoferro157@gmail.com
sentence=Libreria pensata per il controllo PID.
paragraph=Possibilità di usare più controlli PID simultaneamente.
category=Signal Processing
url=
architectures=*